# Generated by Django 2.2.13 on 2020-08-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
